name: Cypress Tests
on: 
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Add this step to set up the Node.js version
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v18.18.0'

      - name: Install dependencies
        run: npm ci
        
      - name: Cypress run
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action 
        uses: cypress-io/github-action@v6
        
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          start: npm run cy:server
          wait-on: 'http://localhost:2525' # Waits for above
          # Records to Cypress Cloud 
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          record: false 
          parallel: false # Runs test in parallel using settings above¨
        env:
          BACKEND_URL: "http://localhost:3002/api/v1"
          ENVIRONMENT: "github"

      - name: Upload Cypress Screenshots
        if: failure()  # Only upload if the tests fail
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots
